/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package erin18062026;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public final class FormMahasiswa extends javax.swing.JFrame {
    MahasiswaNilai mahasiswa = new MahasiswaNilai();
    MahasiswaNilaiController controller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMahasiswa.class.getName());

    /**
     * Creates new form FormMahasiswa
     */
    public FormMahasiswa() {
        initComponents();
        controller = new MahasiswaNilaiController();
        tampilData();
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtUts = new javax.swing.JTextField();
        txtUas = new javax.swing.JTextField();
        txtnilaiAngka = new javax.swing.JTextField();
        txtnilaiHuruf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnProses = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("NIM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 64, 16);

        txtNim.setText("jTextField1");
        getContentPane().add(txtNim);
        txtNim.setBounds(150, 6, 231, 22);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 34, 64, 16);

        txtNama.setText("jTextField2");
        getContentPane().add(txtNama);
        txtNama.setBounds(150, 34, 231, 22);

        txtAlamat.setText("jTextField3");
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(150, 62, 231, 22);

        txtTugas.setText("jTextField4");
        getContentPane().add(txtTugas);
        txtTugas.setBounds(150, 90, 231, 22);

        txtUts.setText("jTextField5");
        getContentPane().add(txtUts);
        txtUts.setBounds(150, 118, 231, 22);

        txtUas.setText("jTextField6");
        getContentPane().add(txtUas);
        txtUas.setBounds(150, 146, 231, 22);

        txtnilaiAngka.setText("jTextField7");
        getContentPane().add(txtnilaiAngka);
        txtnilaiAngka.setBounds(610, 10, 231, 22);

        txtnilaiHuruf.setText("jTextField8");
        getContentPane().add(txtnilaiHuruf);
        txtnilaiHuruf.setBounds(610, 50, 231, 22);

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 65, 64, 16);

        jLabel4.setText("Nilai Tugas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 93, 64, 16);

        jLabel5.setText("UTS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 121, 64, 16);

        jLabel6.setText("UAS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 149, 64, 16);

        jLabel7.setText("Nilai Angka");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 10, 64, 16);

        jLabel8.setText("Nilai Huruf");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(530, 50, 64, 16);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, java.awt.Color.white));
        jPanel1.setLayout(null);

        btnProses.setText("Proses");
        btnProses.addActionListener(this::btnProsesActionPerformed);
        jPanel1.add(btnProses);
        btnProses.setBounds(18, 22, 72, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(440, 90, 110, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.pink, java.awt.Color.white));
        jPanel2.setLayout(null);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel2.add(btnClear);
        btnClear.setBounds(210, 20, 72, 23);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);
        jPanel2.add(btnSimpan);
        btnSimpan.setBounds(10, 20, 72, 23);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel2.add(btnEdit);
        btnEdit.setBounds(110, 10, 72, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 180, 290, 60);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);
        getContentPane().add(btnCari);
        btnCari.setBounds(410, 20, 72, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Tugas", "UTS", "UAS", "Angka", "Huruf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 260, 860, 250);

        setSize(new java.awt.Dimension(899, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        mahasiswa.setNim(txtNim.getText());
        mahasiswa.setNama(txtNama.getText());
        mahasiswa.setAlamat(txtAlamat.getText());
        mahasiswa.setTugas(Double.valueOf(txtTugas.getText()));
        mahasiswa.setUts(Double.valueOf(txtUts.getText()));
        mahasiswa.setUas(Double.valueOf(txtUas.getText()));
        txtnilaiAngka.setText(String.valueOf(mahasiswa.getNilaiAngka()));
        txtnilaiHuruf.setText(mahasiswa.getNilaiHuruf());
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        MahasiswaNilai mhs = new MahasiswaNilai();
        mhs.setNim(txtNim.getText());
        mhs.setNama(txtNama.getText());
        mhs.setAlamat(txtAlamat.getText());
        mhs.setTugas(Double.parseDouble(txtTugas.getText()));
        mhs.setUts(Double.parseDouble(txtUts.getText()));
        mhs.setUas(Double.parseDouble(txtUas.getText()));
        String pesan = controller.insert(mhs);
        JOptionPane.showMessageDialog(this, pesan); 
        tampilData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
         MahasiswaNilai mhs = new MahasiswaNilai();
        mhs.setNim(txtNim.getText());
        mhs.setNama(txtNama.getText());
        mhs.setAlamat(txtAlamat.getText());
        mhs.setTugas(Double.parseDouble(txtTugas.getText()));
        mhs.setUts(Double.parseDouble(txtUts.getText()));
        mhs.setUas(Double.parseDouble(txtUas.getText()));
        String pesan = controller.update(mhs.getNim(), mhs);
        JOptionPane.showMessageDialog(this, pesan); 
        tampilData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         tampilForm(txtNim.getText()); 
    }//GEN-LAST:event_btnCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    private javax.swing.JTextField txtnilaiAngka;
    private javax.swing.JTextField txtnilaiHuruf;
    // End of variables declaration//GEN-END:variables
public void clear(){
    txtNim.setText("");
    txtNama.setText("");
    txtAlamat.setText("");
    txtTugas.setText("");
    txtUts.setText("");
    txtUas.setText("");
    txtnilaiAngka.setText("");
    txtnilaiHuruf.setText("");
    
}

public void tampilData() {
        MahasiswaNilai[] data = controller.getAll();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (MahasiswaNilai mhs : data) {
            Object[] row = {
                mhs.getNim(),
                mhs.getNama(),
                mhs.getTugas(),
                mhs.getUts(),
                mhs.getUas(),
                mhs.getNilaiAngka(),
                mhs.getNilaiHuruf()
            };
            model.addRow(row); 
        }
    }
    
    public void tampilForm(String nim) {
        MahasiswaNilai mhs = controller.getByNim(nim);
        if(mhs!= null) {
        txtNim.setText(mhs.getNim());
        txtNama.setText(mhs.getNama());
        txtAlamat.setText(mhs.getAlamat());
        txtTugas.setText(String.valueOf(mhs.getTugas()));
        txtUts.setText(String.valueOf(mhs.getUts()));
        txtUas.setText(String.valueOf(mhs.getUas()));
        txtnilaiAngka.setText(String.valueOf(mhs.getNilaiAngka()));
        txtnilaiHuruf.setText(mhs.getNilaiHuruf());
        } else {
            JOptionPane.showMessageDialog(this, "Mahasiswa Tidak ada");
        }
    }

}
